# 20 studentů jako tuple (jméno, věk, obor)
studenti_tuple = [
    ("Jan Novák", 20, "informatika"),
    ("Marie Svobodová", 22, "matematika"),
    ("Petr Dvořák", 19, "fyzika"),
    ("Lucie Němcová", 21, "ekonomie"),
    ("Tomáš Černý", 23, "informatika"),
    ("Karolína Procházková", 20, "matematika"),
    ("Jakub Kučera", 18, "informatika"),
    ("Tereza Veselá", 22, "fyzika"),
    ("Martin Horák", 21, "ekonomie"),
    ("Veronika Marková", 19, "informatika"),
    ("Filip Pospíšil", 24, "matematika"),
    ("Anna Králová", 20, "fyzika"),
    ("David Beneš", 22, "ekonomie"),
    ("Kristýna Růžičková", 19, "informatika"),
    ("Ondřej Fiala", 21, "matematika"),
    ("Barbora Malinová", 23, "fyzika"),
    ("Michal Sedláček", 20, "ekonomie"),
    ("Nikola Doležalová", 18, "informatika"),
    ("Adam Nguyen", 22, "fyzika"),
    ("Eliška Krejčí", 21, "matematika"),
]

# 20 položek zboží jako tuple (název, cena, kategorie)
zbozi_tuple = [
    ("Notebook Dell", 25000.0, "elektronika"),
    ("Myš Logitech", 450.0, "elektronika"),
    ("Klávesnice", 890.0, "elektronika"),
    ("Monitor 24\"", 4500.0, "elektronika"),
    ("Sluchátka", 1200.0, "elektronika"),
    ("Python pro začátečníky", 599.0, "knihy"),
    ("Čistý kód", 749.0, "knihy"),
    ("Design Patterns", 899.0, "knihy"),
    ("Algoritmy", 650.0, "knihy"),
    ("Databáze", 720.0, "knihy"),
    ("Tričko", 299.0, "obleceni"),
    ("Mikina", 799.0, "obleceni"),
    ("Džíny", 1200.0, "obleceni"),
    ("Boty", 1850.0, "obleceni"),
    ("Bunda", 2500.0, "obleceni"),
    ("Fotbalový míč", 450.0, "sport"),
    ("Fitness láhev", 199.0, "sport"),
    ("Jóga podložka", 350.0, "sport"),
    ("Činky 2kg", 599.0, "sport"),
    ("Běžecké boty", 2200.0, "sport"),
]